### PR TITLE
Py3 unicode compat; example apt.conf.d file

### PR DESCRIPTION
**Pull request by akatrevorjay**

### CODE REVIEW

**Comment by rahiel** [comment]
Thanks for your PR, I've cherry-picked your 2nd commit to master. About the first one: I don't support python 2 so we don't need six, and unicode shouldn't give a problem unless there exist programs with unicode names.

That last commit is unnecessary: the deb package is using dpkg-triggers on the directory `/usr/share/applications`, so whenever a desktop file changes there, dpkg will automatically run `firectl restore`.

**Comment by akatrevorjay** [comment]
Great about the last commit, for some reason it doesn't work for me however, oh well, I'll keep my fix in place.

**Comment by akatrevorjay** [comment]
About the first, it is needed on a standard Ubuntu install because the characters inside of some desktop files aren't fully `utf8` compatible.

**Comment by rahiel** [comment]
Thanks for your clarification!

> About the first, it is needed on a standard Ubuntu install because the characters inside of some desktop files aren't fully utf8 compatible.

Could you tell an example desktop file it is, or for which package? And what the error is here?

> Great about the last commit, for some reason it doesn't work for me however, oh well, I'll keep my fix in place.

Weird, but happy your fix works.

**Pull request closed without merging**
